apiVersion: v1
kind: Service
metadata:
  name: sf-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    id: {{ template "pod.id" . }} # label of our pod
  type: LoadBalancer
