apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: t
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t
  template:
    metadata:
      labels:
        app: t
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
      restartPolicy: Always
