apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v --volumes persistentVolumeClaim -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: localhost:5000/wuestkamp_nginx #eu.gcr.io/wuestkamp-221618/wuestkamp_nginx
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}


#        env:
#        - name: APP_ENV
#          valueFrom:
#            secretKeyRef:
#              name: sf-env
#              key: APP_ENV
#        - name: APP_SECRET
#          valueFrom:
#            secretKeyRef:
#              name: sf-env
#              key: APP_SECRET



        volumeMounts:
        - mountPath: /var/log/nginx
          name: nginx-claim0
        #- mountPath: /var/www/symfony/public/assets
        #  name: nginx-claim1
        - mountPath: /etc/nginx/ssl
          name: secret-volume
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: nginx-claim0
        persistentVolumeClaim:
          claimName: nginx-claim0
      - name: secret-volume
        secret:
          secretName: nginxsecret
status: {}
