apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v --volumes persistentVolumeClaim -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
      - image: localhost:5000/wuestkamp_php #eu.gcr.io/wuestkamp-221618/wuestkamp_php:latest
        name: php
        ports:
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /var/www/symfony/var/log
          name: php-claim0
        env:
        - name: APP_ENV
          value: prod
        - name: MAILER_URL
          value: smtp://smtp.sendgrid.net:465?encryption=ssl&auth_mode=login&username=apikey&password=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
      restartPolicy: Always
      volumes:
      - name: php-claim0
        persistentVolumeClaim:
          claimName: php-claim0
status: {}
