apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        id: php
    spec:
      containers:
      - image: localhost:5000/wuestkamp_php
        name: php
        ports:
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /var/www/symfony/var/log
          name: php-claim0
        env:
        - name: APP_ENV
          value: dev
      restartPolicy: Always
      volumes:
      - name: php-claim0
        persistentVolumeClaim:
          claimName: php-claim0
status: {}
