apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sf-deployment
  labels:
    id: sf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      id: sf
  template:
    metadata:
      labels:
        id: sf
    spec:
      containers:
      - image: localhost:5000/wuestkamp_nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/symfony/public
            name: sf-public

      - image: localhost:5000/wuestkamp_php
        imagePullPolicy: Always
        name: php
        volumeMounts:
        - mountPath: /vol/sf-public
          name: sf-public
        readinessProbe:
          exec:
            command: ['sh', '-c', 'cp -r /var/www/symfony/public/* /vol/sf-public/; true;']
        env:
        - name: APP_ENV
          value: dev
      restartPolicy: Always

      volumes:
        - name: sf-public
          emptyDir: {}